<a href="https://colab.research.google.com/github/Sebastianpastrana/AnaliticadeDatos/blob/main/Valores_nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importamos las librerias pandas numpy y matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as pit

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload();

Saving inmuebles2.csv to inmuebles2 (1).csv

In [ ]:
#Carga desde un archivo .csv sin indice
data=pd.read_csv("inmuebles2.csv")
data.head(5)

,Unnamed: 0,Esta es una base de datos que describe las operaciones inmobiliarias de una empresa,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291,2133903,2004-06-19 00:00:00,Carmen
2,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185,1945424,2004-04-19 00:00:00,Pedro
3,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82,NaN,2004-11-08 00:00:00,Joaquín
4,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285,NaN,2004-04-27 00:00:00,Jesús

In [ ]:
#Eliminar primera fila o filas innecesariaas
data1=pd.read_csv("inmuebles2.csv",skiprows=1)
data1

,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,5,5,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...,...,...
3332,3333,3333,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,3334,3334,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,3335,3335,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,3336,3336,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,3337,3337,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [ ]:
#Eliminar columnas innecesarias
data2= data1.drop(['0','Referencia'],axis=1)
data2

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [ ]:
#Identificar valores nulos por columnas
valoresnulos=data2.isnull().sum()
valoresnulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

**Métodos Sustitucion de valores nulos.**

In [ ]:
#Realizamos una copia de dataframe
data3=data2.copy()

In [ ]:
#Primer metodo de sustitucion de valores nulos
#Sutituir valores nulos con promedio o media
data3['Superficie']=data3['Superficie'].fillna(round(data2['Superficie'].mean(),1))

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
#Segundo metodo de sustitucion de valores nulos
#Sutituir valores nulos con mediana
data3['Precio Venta']=data3['Superficie'].fillna(round(data2['Superficie'].median(),1))

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
#Tercer metodo de sustitucion de valores nulos
#Sutituir valores nulos con una constante que nosotros escogemos
data3['Fecha Alta']=data3['Fecha Alta'].fillna(10)

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
#Cuarto metodo de sustitucion de valores nulos
#Sutituir valores nulos con un string en concreto
data3['Fecha Venta']=data3['Fecha Venta'].fillna("2030-06-19 00:00:00")

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [ ]:
#Quinto metodo de sustitucion de valores nulos
#Sutituir valores nulos por el valor no nulo siguiente
data3['Tipo']=data3['Tipo'].fillna(method="ffill")

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta        0
Tipo              0
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [ ]:
#Sexto metodo de sustitucion de valores nulos
#Sutituir valores nulos por el valor no nulo anterior
data3['Vendedor']=data3['Vendedor'].fillna(method="bfill")

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta        0
Tipo              0
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        291
dtype: int64

In [ ]:
#Acabamos de sustituir todos los valores nulos
data3['Operación']=data3['Operación'].fillna(method="bfill")
data3['Provincia']=data3['Provincia'].fillna(method="bfill")
data3['Vendedor']=data3['Vendedor'].fillna(10)

In [ ]:
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data3.isnull().sum()
valoresnulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
Pronvinia       0
Pronvincia      0
dtype: int64

**Eliminación de valores nulos**

In [ ]:
#Hacemos una copia
data4=data2.copy

In [ ]:
#Eliminamos los valores nulos
data4=data2.dropna()
#Comprobamos que ya no tengamos valores nulos
valoresnulos=data4.isnull().sum()
valoresnulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64